package demo.booking.hairsalon.controller;

import demo.booking.hairsalon.common.ApiResponse;
import demo.booking.hairsalon.model.dto.request.UpdateProfileRequest;
import demo.booking.hairsalon.model.dto.response.UserProfileResponse;
import demo.booking.hairsalon.service.UserService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

@RestController
@RequiredArgsConstructor
@RequestMapping("/api/user")
public class UserController {

    private final UserService userService;
    private final demo.booking.hairsalon.service.AuthService authService;
    private final demo.booking.hairsalon.service.NotificationService notificationService;
    private final demo.booking.hairsalon.repository.UserRepository userRepository;

    @GetMapping("/profile")
    @PreAuthorize("isAuthenticated()")
    public ApiResponse<UserProfileResponse> getProfile() {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        return ApiResponse.success(userService.getProfile(email), "Profile retrieved successfully", null);
    }

    @PutMapping("/profile")
    @PreAuthorize("isAuthenticated()")
    public ApiResponse<UserProfileResponse> updateProfile(@Valid @RequestBody UpdateProfileRequest request) {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        return ApiResponse.success(userService.updateProfile(email, request), "Profile updated successfully", null);
    }

    @PostMapping("/change-password")
    @PreAuthorize("isAuthenticated()")
    public ApiResponse<Void> changePassword(@Valid @RequestBody demo.booking.hairsalon.model.dto.request.ChangePasswordRequest request) {
        authService.changePassword(request);
        return ApiResponse.success(null, "Password changed successfully", null);
    }

    @GetMapping("/notifications")
    @PreAuthorize("isAuthenticated()")
    public ApiResponse<java.util.List<demo.booking.hairsalon.model.dto.response.NotificationResponse>> getNotifications() {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        return ApiResponse.success(notificationService.getUserNotifications(email), "Notifications retrieved successfully", null);
    }

    @PostMapping("/test-notification")
    @PreAuthorize("isAuthenticated()")
    public ApiResponse<Void> testNotification() {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        demo.booking.hairsalon.model.entity.User user = userRepository.findByEmail(email).orElseThrow();
        notificationService.sendNotification(user, "Test Notification", "This is a test notification generated by API.", "system");
        return ApiResponse.success(null, "Test notification sent successfully", null);
    }

    @PatchMapping("/notifications/{id}/read")
    @PreAuthorize("isAuthenticated()")
    public ApiResponse<Void> markNotificationAsRead(@PathVariable java.util.UUID id) {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        notificationService.markAsRead(id, email);
        return ApiResponse.success(null, "Notification marked as read successfully", null);
    }
}
