spring.application.name=${SPRING_APPLICATION_NAME:hairsalon}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT}

app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration=${JWT_ACCESS_EXPIRATION:900000}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

app.token.verification-expiration=${TOKEN_VERIFICATION_EXPIRATION:86400000}
app.token.password-reset-expiration=${TOKEN_PASSWORD_RESET_EXPIRATION:1800000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.google.client-id=${GOOGLE_CLIENT_ID}